# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.12.3
_src_path: gl:openscm/copier-core-python-repository
conda_release: false
email: florence.bockting@climate-resource.com
include_cli: false
name: Florence Bockting
notebook_based_docs: false
package_manager: uv
pandas_doctests: false
plot_dependencies: true
project_description_short: Intercomparison of CMIP7 data with earth observations as
    part of GHG forcing for CMIP project.
project_name_human: GHG-forcing-for-CMIP-comparison
project_name_pip: ghg-forcing-for-cmip-comparison
project_name_python: ghg_forcing_for_cmip_comparison
project_url: https://github.com/climate-resource/GHG-forcing-for-CMIP-comparison
track_lock_file: true
